### ISSUE TITLE
Podatki

### ISSUE THREAD

**Issue by Anchiqua** [lencdo/Studentski-servis#2]
Pri studenti.csv sem dodali nov stolpec, ki vsebuje ID univerze. Ker imamo podatke za študente generirane, sem tudi random generirala ID univerze in ga dodala študentu. V studenti.py je zapisana koda, kako sem odprla csv datoteko in dodala stolpec, vendar sem morala vse zapisati v novo csv datoteko (studenti1.csv). Zanima me, ali prvotno datoteko lahko zbrišem, saj nam ne koristi več, ali naj jo zaradi evidence pustim?

**Comment by jaanos** [comment]
Odločitev je vaša. Glede na to, da je vse na gitu, lahko do prvotne datoteke tako ali tako dostopate, če želite. Tako jo lahko pobrišete iz aktualne različice repozitorija.
